[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --include=dev --include=optional"]

[phases.build]
cmds = [
  "cd server && npm install --include=dev --include=optional",
  "cd ../client && npm install --include=dev --include=optional",
  "cd .. && npm run build"
]

[start]
cmd = "npm start"

