[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --include=dev || npm install"]

[phases.build]
cmds = ["cd server && npm ci --include=dev || npm install", "cd ../client && npm ci --include=dev || npm install", "cd .. && npm run build"]

[start]
cmd = "npm start"

