[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "rm -rf node_modules package-lock.json .npm",
  "npm cache clean --force",
  "npm install",
  "cd server && rm -rf node_modules package-lock.json .npm && npm cache clean --force && npm install",
  "cd ../client && rm -rf node_modules package-lock.json .npm && npm cache clean --force && npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

