[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --production=false || npm install"]

[phases.build]
cmds = ["npm run install:all", "npm run build"]

[start]
cmd = "npm start"

