[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "cd server && rm -rf node_modules && npm install",
  "cd .. && npm run build"
]

[start]
cmd = "npm start"

