[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npm run install:all && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

